### ISSUE TITLE
Issue with script context and Map<String, Dynamic>

### ISSUE THREAD

**Issue by jefvel** [HeapsIO/hide#82]
I am trying to add a context class to the scripts, as shown in the wiki, using this configuration in `props.json`:
```json
"script.api" : {
		"hx" : {
			"globals" : { "game" : "Game" },
			"context" : "script.Api"
		},
		"cdb.Items" : {
			"globals" : { "game" : "Game" },
			"context" : "script.Api"
		}
	},
```
and `script/Api.hx` looks like this:
```
package script;

class Api {
    public function say(msg : String) {
        trace(msg);
    }

    public var flags : Map<String, Dynamic>;
}
```

When opening HIDE and a script file, the values are autocompleted correctly:
![image](https://user-images.githubusercontent.com/494817/85136316-c0781380-b23f-11ea-98ae-5dd9ae738278.png)

however, it will show an error:
![image](https://user-images.githubusercontent.com/494817/85136398-db4a8800-b23f-11ea-9a65-4550d82eb778.png)
![image](https://user-images.githubusercontent.com/494817/85136596-1ea4f680-b240-11ea-8782-dce3a0b8695c.png)

**Comment by ncannasse** [comment]
Yes Map is an abstract and hscript typer (and interpreter as well - that's most important) does not support abstracts yet. It's a bit hard to deal with since the "api" is remplaced at compilation time, Map being even more complex because it has different implementations depending on the key.

One way to deal with it is to create your own "MyMap" class with get/set methods that holds a private Map abstract.

**Comment by jefvel** [comment]
Okay, good to know, thanks! I'll go with that👍
